name: CI
on: push

permissions:
  contents: read

jobs:

  build:

    name: Build
    runs-on: ubuntu-26.04

    steps:

      - name: Clone kernel source
        uses: actions/checkout@v7
        with:
          repository: torvalds/linux
          ref: master
          path: linux
          persist-credentials: false

      - name: Install build dependencies
        run: sudo apt-get install bc binutils bison dwarves flex gcc git make openssl pahole perl-base libssl-dev libelf-dev build-essential debhelper-compat libdw-dev
        shell: bash

      - name: Tag build
        run: echo "-ff" > localversion
        shell: bash
        working-directory: linux

      - name: Configure build
        # This is not suitable for most use-cases, just a starting point to get
        # a build.
        run: make defconfig
        shell: bash
        working-directory: linux

      - name: Build
        run: make -j "$(nproc --all)" bindeb-pkg
        shell: bash
        working-directory: linux
